version: '3.8'

services:
  aspnetapi:
    build: 
      context: ./aspnetapi/src/.
      dockerfile: ElympicsNet.Api/Dockerfile
    image: elympicsnetapi:latest
    container_name: elympicsnetapi
    environment:
      - postgres__connectionString=Host=postgres;Port=5432;Database=mydatabase2;Username=myuser;Password=mypassword;
      - Entry__MaxFetchedAmount=3
      - gowebapi__url=http://gowebapi:8082
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - gowebapi
    
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase2
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  gowebapi:
    build: 
      context: ./gowebapi/src/.
      dockerfile: Dockerfile
    image: elympicsgowebapi:latest
    container_name: elympicsgowebapi
    ports:
      - "8081:8082"

volumes:
  postgres:
    driver: local