name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yaml build --no-cache
        docker tag elympicsnetapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/elympicsnetapi:latest
        docker tag elympicsgowebapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/elympicsgowebapi:latest

    - name: Run Services
      run: |
        docker-compose -f docker-compose.yaml up -d

    - name: Execute Integration Tests
      run: |
        cd aspnetapi/tests/ElympicsNet.Api.Tests.Integration
        dotnet test

    - name: Push Image to Docker Hub
      run: |
        docker push  ${{ secrets.DOCKERHUB_USERNAME }}/elympicsnetapi:latest
        docker push  ${{ secrets.DOCKERHUB_USERNAME }}/elympicsgowebapi:latest
